### PR TITLE
replace fork by pthread. Avoid USBtty0/1 bug. Better usage. Extensible.

### PR DESCRIPTION
**Pull request by j-levy**
THis has been tested and works. I create a thread instead of using a fork. Some variable are global and common between the two threads, but that's not a problem, because only one thread write on them, and the other one is always only reading repetively (no need for synchronization).
Now, please run this OUTSIDE Visual Studio Code, and use CTRL+P to terminate pc_terminal, in order to avoid zombie thread. Please. The shortcut CTRL+P is not doable inside Visual Studio Code.

### CODE REVIEW

**Review by niketagrawal — COMMENTED** [review]
Changes look fine. Do you still see the log "timeout detected, sending mode as 1" on PC side? We noticed this today afternoon.

**Comment by j-levy** [comment]
There was errors popping out because of a Read-After-Write caused by splitting in two threads and using the time variable *tp*. Implemented a mutex to avoid this.

**Comment by j-levy** [comment]
I changed stuf, seems better. no more mutex that can introduce overhead. Instead, i create my two separate threads, and they loop forever. And only the main is reading the time values. And if there's some time-related thread to be called, namely timeout or sending packet, it raises a flag.

So in particular, the reading is in a separate thread, and the sending is also in a separate thread, making them running concurrently.
This can mean that the packet content can change in-between the packet creation, but that would just cause a wrong packet (wrong CRC in the end). So it will be discarded on the board in any case.

It feels like it's reacting faster, when I try it.

**Comment by j-levy** [comment]
And I just added the support for CTRL+C catch, to quit normally by catching all the threads before returning in the main.

**Pull request merged**
